In [ ]:
# Import modules
import pandas as pd

In [33]:
# Load raw dataset
df = pd.read_csv('juanmart_raw_sales.csv')

In [ ]:
# Identify data anomalies
display(df)

# The formatting of values in column order_date is inconsistent and alternates between - and / as the value separator. The 
# letter case of the strings in region is also inconsistent with some entries having the same string but in different casing.

,transaction_id,cust_name,region,order_date,amount_paid,status
0,1001,Juan Dela Cruz,NCR,2026-07-01,1500.50,Completed
1,1002,Maria Santos,Metro Manila,2026/07/02,2400.00,Completed
2,1003,NaN,ncr,2026-07-02,450.00,Cancelled
3,1004,Pedro Penduko,CALABARZON,2026/07/03,NaN,Completed
4,1005,Ana Roces,calabarzon,2026-07-04,3100.25,Completed
5,1001,Juan Dela Cruz,NCR,2026-07-01,1500.50,Completed
6,1006,Jose Rizal,Region IV-A,2026/07/05,1200.00,Returned
7,1007,Cardo Dalisay,Metro Manila,2026-07-05,NaN,Completed
8,1008,NaN,ncr,2026/07/06,850.75,Completed
9,1005,Ana Roces,calabarzon,2026-07-04,3100.25,Completed
10,1009,Manny Pacquiao,CALABARZON,2026-07-06,5000.00,Completed
11,1010,Catriona Gray,NCR,2026/07/07,1850.00,Cancelled

In [ ]:
df.dtypes

# Column datatypes are as expected.

transaction_id      int64
cust_name             str
region                str
order_date            str
amount_paid       float64
status                str
dtype: object

In [ ]:
df.info()

# RangeIndex reveals that there are 12 entries or rows in the dataset. Columns cust_name and amount_paid have 10 non-null
# entries or, in other words, 2 null entries.

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  12 non-null     int64
 1   cust_name       10 non-null     str
 2   region          12 non-null     str
 3   order_date      12 non-null     str
 4   amount_paid     10 non-null     float64
 5   status          12 non-null     str
dtypes: float64(1), int64(1), str(4)
memory usage: 1.1 KB

'\nRangeIndex reveals that there are 12 entries or rows in the dataset. Columns cust_name and amount_paid have 10 non-null\nentries or, in other words, 2 null entries. \n'

In [ ]:
df.describe()

# describe() reveals the statistics of the numerical columns transaction_id and amount_paid. There are only 10 entries in
# amount_paid out of the expected 12. There are no unexpected negative values in the amount_paid column.

       transaction_id  amount_paid
count       12.000000      10.0000
mean      1005.083333    2095.2250
std          3.028901    1348.8760
min       1001.000000     450.0000
25%       1002.750000    1275.1250
50%       1005.000000    1675.2500
75%       1007.250000    2925.1875
max       1010.000000    5000.0000

In [ ]:
df.isnull().sum()

# This confirms that there are a total of 4 null values in the dataset; two in column cust_name and two in column amount_paid

transaction_id    0
cust_name         2
region            0
order_date        0
amount_paid       2
status            0
dtype: int64

In [ ]:
df.value_counts()

# Reveals that there are two entries that have duplicates in the dataset namely transaction 1001 and 1005.

transaction_id  cust_name       region        order_date  amount_paid  status
1001            Juan Dela Cruz  NCR           2026-07-01  1500.50      Completed    2
1005            Ana Roces       calabarzon    2026-07-04  3100.25      Completed    2
1002            Maria Santos    Metro Manila  2026/07/02  2400.00      Completed    1
1006            Jose Rizal      Region IV-A   2026/07/05  1200.00      Returned     1
1009            Manny Pacquiao  CALABARZON    2026-07-06  5000.00      Completed    1
1010            Catriona Gray   NCR           2026/07/07  1850.00      Cancelled    1
Name: count, dtype: int64

In [ ]:
test = df
test["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")    # convert values into datetime if valid
display(test)

# Rows 1, 3, 6, 8, and 11 have invalid value formats and could not be converted into datetime format.

,transaction_id,cust_name,region,order_date,amount_paid,status
0,1001,Juan Dela Cruz,NCR,2026-07-01,1500.50,Completed
1,1002,Maria Santos,Metro Manila,NaT,2400.00,Completed
2,1003,NaN,ncr,2026-07-02,450.00,Cancelled
3,1004,Pedro Penduko,CALABARZON,NaT,NaN,Completed
4,1005,Ana Roces,calabarzon,2026-07-04,3100.25,Completed
5,1001,Juan Dela Cruz,NCR,2026-07-01,1500.50,Completed
6,1006,Jose Rizal,Region IV-A,NaT,1200.00,Returned
7,1007,Cardo Dalisay,Metro Manila,2026-07-05,NaN,Completed
8,1008,NaN,ncr,NaT,850.75,Completed
9,1005,Ana Roces,calabarzon,2026-07-04,3100.25,Completed
10,1009,Manny Pacquiao,CALABARZON,2026-07-06,5000.00,Completed
11,1010,Catriona Gray,NCR,NaT,1850.00,Cancelled

In [34]:
# Data cleaning
df['order_date'] = df['order_date'].str.replace("-", "/", regex=False)
df['order_date'] = pd.to_datetime(df['order_date'], format='%Y/%m/%d',errors='coerce')
df['region'] = df['region'].str.lower()
df.drop_duplicates(inplace=True)
df['amount_paid'] = df['amount_paid'].fillna(0)
df['cust_name'] = df['cust_name'].fillna('Unknown')

display(df)

,transaction_id,cust_name,region,order_date,amount_paid,status
0,1001,Juan Dela Cruz,ncr,2026-07-01,1500.50,Completed
1,1002,Maria Santos,metro manila,2026-07-02,2400.00,Completed
2,1003,Unknown,ncr,2026-07-02,450.00,Cancelled
3,1004,Pedro Penduko,calabarzon,2026-07-03,0.00,Completed
4,1005,Ana Roces,calabarzon,2026-07-04,3100.25,Completed
6,1006,Jose Rizal,region iv-a,2026-07-05,1200.00,Returned
7,1007,Cardo Dalisay,metro manila,2026-07-05,0.00,Completed
8,1008,Unknown,ncr,2026-07-06,850.75,Completed
10,1009,Manny Pacquiao,calabarzon,2026-07-06,5000.00,Completed
11,1010,Catriona Gray,ncr,2026-07-07,1850.00,Cancelled